apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: voting-app-label
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-app-label
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-app-label
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust