apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app-label    
spec:
  selector:
    name: redis-pod
    app: voting-app-label
  ports:
  - port: 6379
    targetPort: 6379