apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: voting-app-label
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: voting-app-label
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: voting-app-label
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379