apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: voting-app-label    
spec:
  type: NodePort
  selector:
    name: result-pod
    app: voting-app-label
  ports:
  - port: 80
    targetPort: 80