apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: voting-app-label    
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: vote-pod
    app: voting-app-label